# Site settings
title: Marcin Jakuszko
email: marcin.jakuszko@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog Marcina Jakuszko.
  Aspirujący pragmatyk, programista oraz projektant.
  Lifestyle, geek, code - w takiej tematyce osadzone są wpisy autora.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakuszko.eu" # the base hostname & protocol for your site
twitter_username: marcinjakuszko
github_username:  marcinjakuszko

# Build settings
markdown: kramdown

# Custom settings for Casper theme
highliter: pygment #code syntax highliting
paginate: 10 #how many posts should be displayed per page
cover: "/images/cover.jpg" #cover image url to be displayed on index (or false if not)
logo: false #logo url to be displayed on index (or false if not)
author: Marcin Jakuszko #site author
author_image: "/images/author.jpg" #url for author avatar
author_description: Aspirujący pragmatyk, programista i projektant. #author bio
quote: Dobre API jest jak meble z IKEA. #header title

disqus: true #enables or disables Disqus on post pages



